name: Lock Closed Issues

on:
  schedule:
    - cron: '0 1/13 * * *'

jobs:
  lock:
    name: Lock Closed Issues
    if: github.repository == 'Unn4m3DD/OctoPrint-TouchUI'

    runs-on: ubuntu-latest

    steps:
    - uses: dessant/lock-threads@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        process-only: 'issues'
        issue-lock-inactive-days: '14'
        issue-exclude-created-before: ''
        issue-exclude-labels: 'no-locking'
        issue-lock-labels: ''
        issue-lock-comment: >
          This issue has been automatically locked since there
          has not been any recent activity after it was closed.
          Please open a new issue for related bugs.
        issue-lock-reason: ''
